### ISSUE TITLE
Including static assets in lambda upload

### ISSUE THREAD

**Issue by micimize** [gristlabs/aws-lambda-upload#3]
My service requires a cache file that I currently have to add between zip and manual upload, but I'd like to include it in the `updateLambda` call - is there any way to do this through browserify options or something like that?

**Comment by dsagal** [comment]
Sorry, I don't think there is a way to include any non-JS files.

**Comment by micimize** [comment]
wrapping `aws-lambda-upload --zip` is simple enough
```bash
aws lambda update-function-code         \
  --function-name lambda_function       \
  --zip-file fileb://$zipfile           \
```

**Comment by micimize** [comment]
to clarify what how I solved this for passers by, you just zip the lambda and then proceed to add static assets after (you have to know which assets are needed) - 
```bash
yarn aws-lambda-upload --zip $zipfile $graphile/index.js
zip -ur $zipfile $cachefile
zip -ur $zipfile node_modules/graphile-build-pg/res/
aws lambda update-function-code          \
  --function-name my_lambda_function     \
  --zip-file fileb://$zipfile            
```
